CREATE TABLE IF NOT EXISTS `Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(191) NOT NULL UNIQUE,
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(100) NOT NULL,
  `wlen` INT NOT NULL,
  `power` INT NOT NULL,
  `price` INT NOT NULL DEFAULT 0,
  `mode` VARCHAR(20) NOT NULL,
  `image` VARCHAR(500) NOT NULL,
  `blurb` TEXT NOT NULL,
  `tags` TEXT NOT NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'EUR',
  `salePrice` INT NULL,
  `vatPercent` INT NOT NULL DEFAULT 20,
  `availability` VARCHAR(32) NOT NULL DEFAULT 'in_stock',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(191) NOT NULL UNIQUE,
  `title` VARCHAR(255) NOT NULL,
  `excerpt` TEXT NULL,
  `content` LONGTEXT NOT NULL,
  `coverImage` VARCHAR(500) NULL,
  `published` TINYINT(1) NOT NULL DEFAULT 0,
  `publishedAt` DATETIME NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
